package com.lion;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;

import java.util.Objects;

@Entity // add @Entity and @Id annotation to create a table in the database
public class SoftwareEngineer {

    @Id //these 3 fields are now columns in the database
    @GeneratedValue(strategy = GenerationType.IDENTITY) // to automatically generate ids
    private Integer id; //primary key
    private String name;
    private String techStack;

    public SoftwareEngineer() {

    }

    public SoftwareEngineer(Integer id,
                            String name,
                            String techStack) {
        this.id = id;
        this.name = name;
        this.techStack = techStack;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getTechStack() {
        return techStack;
    }

    public void setTechStack(String techStack) {
        this.techStack = techStack;
    }

    @Override // autogenerated equals compares the fields, overrides the one implemented in Object class.
    public boolean equals(Object o) {
        if (o == null || getClass() != o.getClass()) return false;
        SoftwareEngineer that = (SoftwareEngineer) o;
        return Objects.equals(id, that.id) && Objects.equals(name, that.name) && Objects.equals(techStack, that.techStack);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, name, techStack);
    }
}
